### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by Melkiades** [seattlemiles/aim-2019#1]
So, I will try to resume what I believe is the best way to proceed, also considering what we talked about. Any correction or addition is welcomed, of course.

1) **Cleaning of the data** in such a way that every email is described by some major characteristics such as sender, receiver, type of message (answer, forwarding), attachments, time of sending, body, the title of the email. Some other feature that we could consider (if present) is the position inside the company of the sender and receiver at that time and some little aesthetic characteristic like the length of the email or the number of blank lines and so on. Of course, we should remove (momentarily) the answer chains and forward repetitions. Moreover, for each email, I would define a unique id.
2) **Represent this initial data-set in a compact way**. In my opinion, the best way would be by means of a graph of email accounts. In this way, we can already calculate the major hubs of the system (by using a centrality measure, for example). Interestingly this representation can be dynamic, meaning that we can calculate the connection strengths in windows of time and see how the most prominent people change during the 3 years range. This can be interesting to know because of course there have been shifts in power and, considering how it ended, probably who was in charge had major guilts (just an idea). I do not know how to use the other general features but maybe other graphs?? This step could be important because some of the variables (like centrality) must be relevant for point 4. I think that how important is a colleague changes the effect that his sentimental emails have on the company.
3) **Sentiment analysis** of the emails' bodies. In this case, my idea would be to add the results to the list of general characteristics described above. This is, of course, crucial and I would proceed with some classical TF/IDF (or word2vec) and clustering approach or if there is already a pre-trained NN
for sentiment analysis to try it. At this point, we would have a certain number of values that describe the "sentiment" of each email.
4) **Clustering and visualization.** Now we can use many methods for unsupervised clustering but, as Miles said, they primarily need a visual support for reviewers, just to reduce the search space. Therefore, I would suggest producing a t-SNE or UMAP projection with a series of different clustering results. At this point, any refinement, considering also the answer chains and forward trees, would be interesting.

Tell me what you think!! :)

**Comment by mtimpe** [comment]
1. I've added a Jupyter notebook that parses the email content and returns a number of fields, including the sender, recipient(s), cc list, bcc list, date/time, and whether or not it's a response (Re:) or forwarded email (Forwarded by...).

2. Right now, the data from Step 1 is written to a Pandas dataframe. I can also make a sender-recipient network graph, but first we should curate the email addresses because some people have multiple addresses associated with them (including the CEO).

3. The notebook implements a lexicon-based SA on subject lines and sentences.

4. Haven't done any visualization yet...
