### ISSUE TITLE
network analysis

### ISSUE THREAD

**Issue by mtimpe** [seattlemiles/aim-2019#3]
# Network Analysis

What is the best way to quantify the connections between the people in the Enron dataset? Who are the people driving the bulk of emails? How are issues typically elevated within the Enron hierarchy? Are the communications (as quantified by sentiment analysis) between certain people generally positive or negative in tone?

**Comment by rafazh** [comment]
> What is the best way to quantify the connections between the people in the Enron dataset?

Perhaps a distribution for number of emails exchanged between a given sender and single recipients (or small groups)? In case this "individual" recipient is actually a mailing list, this can be filtered out at a different stage.

**Comment by Melkiades** [comment]
I would do this [https://www.kaggle.com/jamestollefson/enron-network-analysis](https://www.kaggle.com/jamestollefson/enron-network-analysis)

**Comment by Melkiades** [comment]
I made the network but there are problems yet on how to select the emails to consider. I filtered for @enron and senders but maybe we should discuss about it. I found also previous work that was focusing on the crisis period with centrality measures. You can find it [here](https://pdfs.semanticscholar.org/4d7d/8fe43f391a966e0e15b68e6509fe6b533540.pdf).
