### ISSUE TITLE
Number of emails after filtering

### ISSUE THREAD

**Issue by Melkiades** [seattlemiles/aim-2019#4]
As @fcocin pointed out in his commit c7103d0f373f50ed0da68b5213ccd2c252c61154, there is a huge miss-match between the number of emails found by him and miles. Also, I calculated that the number of email in all the /sent$ folders are 58257. Note that the original corpus had 0.5M (so it has been, as we thought pre-processed). Filtering the forwarded emails with no text addition we obtained ~54k emails. Why in the ".csv" files there is this large difference in the number of emails?

**Comment by mtimpe** [comment]
I also see about ~54k emails, however the notebook is operating only on a small subset for testing. I'm not sure where EY got this dataset from, but it is indeed not the full 500k that you can find online...

**Comment by Melkiades** [comment]
Yes, I was just confirming that is a selected data set. The problem is this discrepancy:
```
$ wc -l *.csv 
   50595 mail_corpus.csv
    1602 sent.csv
   52197 total

```

**Comment by mtimpe** [comment]
I'll generate a new sent.csv on the full sent folder now so we can compare. At the moment, the eda.ipynb is set to only use the emails from the first 10 people in the maildir (in order to speed up testing) and therefore only outputs ~1.5k emails.

**Comment by mtimpe** [comment]
I uploaded a new sent.csv file and few basic visualizations. There are ~59k rows in the csv now, but there might be some duplicates in there. Will fix that in the morning.
